import './globals.css'
import Navbar from '../components/navbar'
import Information from '../components/information'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <link rel="shortcut icon" type="image/x-icon" href="../public/ecar-logo.ico" />
      </head>
      <body className={inter.className}>
        <header>
          <Navbar />
        </header>  
        {children}
        <footer>
          <Information />
        </footer>
      </body>
    </html>
  )
}
